resources:
- 01-namespaces/cicd-environment.yaml
- 01-namespaces/jclaret-environment.yaml
- 02-rolebindings/internal-registry-jclaret-binding.yaml
- 02-rolebindings/pipeline-service-account.yaml
- 02-rolebindings/pipeline-service-role.yaml
- 02-rolebindings/pipeline-service-rolebinding.yaml
- 03-tasks/deploy-from-source-task.yaml
- 04-pipelines/app-ci-pipeline.yaml
- 04-pipelines/ci-dryrun-from-push-pipeline.yaml
- 05-bindings/dev-app-taxi-taxi-binding.yaml
- 05-bindings/github-push-binding.yaml
- 06-templates/app-ci-build-from-push-template.yaml
- 06-templates/ci-dryrun-from-push-template.yaml
- 07-eventlisteners/cicd-event-listener.yaml
- 08-routes/gitops-webhook-event-listener.yaml
